# fly.toml app configuration file generated for chat-mariupol on 2026-06-03T13:24:11-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'chat-mariupol'
primary_region = 'ams'

[build]
  dockerfile = 'Dockerfile'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 100
    soft_limit = 80

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
